# Generated by Django 3.1.7 on 2021-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210224_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
