# Generated by Django 3.1.7 on 2021-02-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210224_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauser',
            name='email',
        ),
        migrations.AlterField(
            model_name='datauser',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
