# Generated by Django 3.1.7 on 2021-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210224_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='fio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
